<?php

/**
 * @file
 * ek_address_book module .
 */

/**
 * Implementation hook ek_home.
 */
function ek_address_book_ek_home() {
    $build = [];
    $build[] = [
        'name' => 'address_book',
        'module' => 'Address book',
        'stamp' => 1586604000,
        'type' => 'new',
        'content' => '<a href="/address_book">Address book</a>: new fields available for State and company registration number.',
        'footer' => 'April 2020',
    ];

    return $build;
}

/**
 * Implementation hook download.
 */
function ek_address_book_file_download($uri) {

  if (strpos($uri ?? "",'address_book/cards/')) {
      // Check that the file exists and is an image.
      $image = \Drupal::service('image.factory')->get($uri);
      if ($image->isValid()) {
      
          return array(
            // Send headers describing the image's size, and MIME-type.
            'Content-Type' => $image->getMimeType(),
            'Content-Length' => $image->getFileSize(),
            // By not explicitly setting them here, this uses normal Drupal
            // Expires, Cache-Control and ETag headers to prevent proxy or
            // browser caching of private images.
          );
        
      }
  }
}

/**
 * Implementation hook_theme().
 */
function ek_address_book_theme() {
  return array(
    'ek_address_book_card' => [
      'template' => 'ek_address_book_card',
      'variables' => ['items' => []],
    ], 
    'ek_address_book_form' => [
      'template' => 'ek_address_book_form',
      'variables' => ['items' => []],
    ], 
    // for the lookup card form
    'ek_address_book_search_form' => [
      'template' => 'ek_address_book_search_form',
      'variables' => ['items' => []],
    ], 
    // for entry of single name card
    'ek_address_book_card_form' => [
      'template' => 'ek_address_book_form',
      'variables' => ['items' => []],
    ],    
    'ek_address_book_tip' => [
      'template' => 'ek_address_book_tip',
      'variables' => ['items' => []],
    ],          
    'edit_contact_form' => [
      'render element' => 'form'
    ],
  );     
}


function template_preprocess_ek_address_book_card(&$variables) {                                 
  
}

function template_preprocess_ek_address_book_form(&$variables) {

$form = $variables['items'];

$row1[] = array(  
    'data' => array(
        ['data' => $form['name'],'width' => '50%','bgcolor' => '','colspan' => 2],
        ['data' => $form['shortname'],],
        
      ),
      'class' => [] ,
    );

$row1[] = array(
    'data' => array(
       ['data' => $form['reg'],  'colspan' => 1],
        ['data' => $form['status'],  'colspan' => 2 ],
      ),
      'class' => [] ,
    );

$row1[] = array(
        array('data' => ['#markup' => "<div id='alert' ></div>"], 'colspan' => 3 ),
    );


$row2[] = array(  
    'data' => array(
        ['data' => $form['address'], 'width' => '50%', 'bgcolor' => ''],
        ['data' => $form['city'], ],
        ['data' => $form['postcode'],],
      ),
      'class' => [] ,
    );  

$row2[] = array(  
      'data' => array(
        ['data' => $form['address2'], 'width' => '50%', 'bgcolor' => ''],
        ['data' => $form['state'], 'colspan' => 1 ],
        ['data' => $form['country'], 'colspan' => 1 ],
      ),
      'class' => [] ,
    );

$row3[] = array(  
      'data' => array(
        ['data' => $form['telephone'],],
        ['data' => $form['fax'],],
        ['data' => $form['website'],],
      ),
      'class' => [] ,
    );

$row4[] = array(  
      'data' => array(
        ['data' => $form['type'],],
        ['data' => $form['category'],],
        ['data' => $form['tags'],],
      ),
      'class' => [] ,
    );
$row5[] = array(  
      'data' => array(
        ['data' => $form['logo'],],
        ['data' => $form['currentlogo'],],
        ['data' => $form['delete_logo'],],
      ),
      'class' => [] ,
    );    
unset($form['name'], 
  $form['shortname'], 
  $form['status'], 
  $form['address'],
  $form['address2'],
  $form['state'],
  $form['city'],
  $form['postcode'], 
  $form['country'],
  $form['reg'],      
  $form['telephone'],
  $form['fax'],
  $form['website'],
  $form['type'],
  $form['category'],
  $form['tags'],
  $form['currentlogo'],
  $form['delete_logo'],
  $form['logo']      
);

    
$variables['form'] = $form;

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row1,
  );

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row2,
  );

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row3,
  );

  
$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row4,
  );

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row5,
  );
}

function template_preprocess_ek_address_book_card_form(&$variables) {

$form = $variables['items'];
$variables['form'] = $form;

}

