<?php
    ///////////////////////////////////////////////////
    //                  COPYRIGHT                    //
    //                                               //
    // DEVELOPED BY ARREA LTD                       //
    // all rights reserved                           //
    // Please read and agree with software           //
    // application license                           //
    ///////////////////////////////////////////////////

/**
 * @file
 * ek_address_book module .
 */


/**
 * Implementation hook download.
 */
function ek_address_book_file_download($uri) {

if (strpos($uri,'address_book/cards/')) {
    // Check that the file exists and is an image.
    $image = \Drupal::service('image.factory')->get($uri);
    if ($image->isValid()) {
     
        return array(
          // Send headers describing the image's size, and MIME-type.
          'Content-Type' => $image->getMimeType(),
          'Content-Length' => $image->getFileSize(),
          // By not explicitly setting them here, this uses normal Drupal
          // Expires, Cache-Control and ETag headers to prevent proxy or
          // browser caching of private images.
        );
      
    }
//return array('Content-Type' => \Drupal::service('file.mime_type.guesser')->guess($uri));
}
}

/**
 * Implementation hook_theme().
 */
function ek_address_book_theme() {
  return array(
  
    'ek_address_book_card' => array
    (
      'template' => 'ek_address_book_card',
      'variables' => array('items' => array()),
    ), 
    'ek_address_book_form' => array
    (
      'template' => 'ek_address_book_form',
      'variables' => array('items' => array()),
    ), 
    
    // for the lookup card form
    'ek_address_book_search_form' => array
    (
      'template' => 'ek_address_book_search_form',
      'variables' => array('items' => array()),
    ), 
    // for entry of single name card
    'ek_address_book_card_form' => array
    (
      'template' => 'ek_address_book_form',
      'variables' => array('items' => array()),
    ),    
         
    'edit_contact_form' => array
    (
      'render element' => 'form'
    ),   
    
  );     
}


function template_preprocess_ek_address_book_card(&$variables) {                                 
  
}

function template_preprocess_ek_address_book_form(&$variables) {

$form = $variables['items'];

$row1[] = array(  
      'data' => array(
        array ('data' => $form['name'], 'width' => '50%', 'bgcolor' => ''),
        array('data' => $form['shortname'], ),
        array('data' => $form['status'],  ),
      ),
      'class' => array('') ,
    );
$row1[] = array(
        array('data' => array('#markup' => "<div id='alert' ></div>"), 'colspan' => 3 ),
    );
    
$row2[] = array(  
      'data' => array(
        array ('data' => $form['address'], 'width' => '50%', 'bgcolor' => ''),
        array('data' => $form['city'], ),
        array('data' => $form['postcode'],  ),
      ),
      'class' => array('') ,
    );  

$row2[] = array(  
      'data' => array(
        array ('data' => $form['address2'], 'width' => '50%', 'bgcolor' => ''),
        array('data' => $form['country'], 'colspan' => 2 ),

      ),
      'class' => array('') ,
    );

$row3[] = array(  
      'data' => array(
        array ('data' => $form['telephone'], ),
        array('data' => $form['fax'],),
        array('data' => $form['website'],),
      ),
      'class' => array('') ,
    );

$row4[] = array(  
      'data' => array(
        array ('data' => $form['type'], ),
        array('data' => $form['category'],),
        array('data' => $form['tags'],),
      ),
      'class' => array('') ,
    );
    
unset($form['name'], 
  $form['shortname'], 
  $form['status'], 
  $form['address'],
  $form['address2'],
  $form['city'],
  $form['postcode'], 
  $form['country'],
  $form['telephone'],
  $form['fax'],
  $form['website'],
  $form['type'],
  $form['category'],
  $form['tags']
);

    
$variables['form'] = $form;

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row1,
  );

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row2,
  );

$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row3,
  );

  
$variables['form'][] =  array(
  '#theme' => 'table',
  '#header' => '',
  '#rows' => $row4,
  );

}

function template_preprocess_ek_address_book_card_form(&$variables) {

$form = $variables['items'];
$variables['form'] = $form;

}



/**
 * Implements hook_views_data().
 */
function ek_address_book_views_data() {
  
  $data['ek_address_book']['table']['group'] = t('ek address book');

  // Define this as a base table – a table that can be described in itself by
  // views (and not just being brought in as a relationship). 
  $data['ek_address_book']['table']['base'] = array(
    'field' => 'id', // This is the identifier field for the view.
    'title' => t('ek address book'),
    'help' => t('ek address book contains address book data.'),
    'database' => 'external_db',
    'weight' => -10,
  );

  // This table references the {_contacts} table. The declaration below creates an
  // 'implicit' relationship to the _contacts table, so that when '_contacts' is the base
  // table, the fields are automatically available.
  $data['ek_address_book']['table']['join'] = array(
    // Index this array by the table name to which this table refers.
    // 'left_field' is the primary key in the referenced table.
    // 'field' is the foreign key in this table.
    'database' => 'external_db',
    'ek_address_book_contacts' => array(
      'left_field' => 'abid',
      'field' => 'id',
      'database' => 'external_db',
    ),
      
  );

  $data['ek_address_book']['id'] = array(
    'title' => t('address book id'),
    'help' => t('address book id'),
    'relationship' => array(
      'base' => 'ek_address_book_contacts', // The name of the table to join with
      'field' => 'abid', // The name of the field to join with
      'id' => 'standard',
      'label' => t('Contact in this address book entry'),
    ),
        'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'numeric',
    ),
  );

  $data['ek_address_book']['name'] = array(
    'title' => t('name'),
    'help' => t('entry name'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book']['shortname'] = array(
    'title' => t('short name'),
    'help' => t('a short name used in ref.'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book']['address'] = array(
    'title' => t('address'),
    'help' => t('address first line'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );  
  
  $data['ek_address_book']['address2'] = array(
    'title' => t('address2'),
    'help' => t('address second line'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );  

  $data['ek_address_book']['postcode'] = array(
    'title' => t('postcode'),
    'help' => t('address postcode'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );  
  
  $data['ek_address_book']['city'] = array(
    'title' => t('city'),
    'help' => t('address city'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );   

  $data['ek_address_book']['country'] = array(
    'title' => t('country'),
    'help' => t('address country'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  ); 

  $data['ek_address_book']['telephone'] = array(
    'title' => t('telephone'),
    'help' => t('main phone line'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  ); 


  $data['ek_address_book']['fax'] = array(
    'title' => t('fax'),
    'help' => t('main fax line'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  ); 

  $data['ek_address_book']['website'] = array(
    'title' => t('website'),
    'help' => t('website'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );
  
  $data['ek_address_book']['type'] = array(
    'title' => t('type'),
    'help' => t('type: 1 client, 2 supplier, 3 other'),
    'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'numeric',
    ),
  );   
      
      
  $data['ek_address_book']['category'] = array(
    'title' => t('category'),
    'help' => t('type: 1 head office'),
    'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'numeric',
    ),
  );       

  $data['ek_address_book']['activity'] = array(
    'title' => t('activity'),
    'help' => t('activity ref. from taxonomy'),
    'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'numeric',
    ),
    'relationship' => array(
      'base' => 'taxonomy_term_data', // The name of the table to join with
      'field' => 'tid', // The name of the field to join with
      'id' => 'standard',
      'label' => t('activity listed in taxonomy'),
    ),    
    
  );   

  $data['ek_address_book']['status'] = array(
    'title' => t('status'),
    'help' => t('status: 1 active, 0 non active'),
    'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'numeric',
    ),
  );       

  //timestamp field.
  $data['ek_address_book']['stamp'] = array(
    'title' => t('timestamp field'),
    'help' => t('timestamp field'),
    'field' => array(
      'id' => 'date',
    ),
    'sort' => array(
      'id' => 'date',
    ),
    'filter' => array(
      'id' => 'date',
    ),
  );




  $data['ek_address_book_contacts']['table']['group'] = t('ek address book contacts');
  $data['ek_address_book_contacts']['table']['base'] = array(
    'field' => 'id', // This is the identifier field for the view.
    'title' => t('ek address book contacts'),
    'help' => t('ek address book contains address book contact name data.'),
    'weight' => -10,
    'database' => 'external_db',
  );

  // This table references the {_contacts} table. The declaration below creates an
  // 'implicit' relationship to the _contacts table, so that when '_contacts' is the base
  // table, the fields are automatically available.
  $data['ek_address_book_contacts']['table']['join'] = array(
    // Index this array by the table name to which this table refers.
    // 'left_field' is the primary key in the referenced table.
    // 'field' is the foreign key in this table.
    'ek_address_book' => array(
      'left_field' => 'id',
      'field' => 'abid',
      'database' => 'external_db',
    ),
  );

  //  ID table field.
  $data['ek_address_book_contacts']['id'] = array(
    'title' => t('Contact book id'),
    'help' => t('Contact book contact id'),
       'field' => array(
       'id' => 'numeric',
    ),
       'sort' => array(
       'id' => 'standard',
    ),
       'filter' => array(
       'id' => 'numeric',
    ),
  );
  
  $data['ek_address_book_contacts']['abid'] = array(
    'title' => t('Main address book contact id'),
    'help' => t('Main address book contact id ref.'),
    'relationship' => array(
      'base' => 'ek_address_book', // The name of the table to join with
      'field' => 'id', // The name of the field to join with
      'id' => 'standard',
      'label' => t('Main address book entry'),
    ),
       'field' => array(
       'id' => 'numeric',
    ),
       'sort' => array(
       'id' => 'standard',
    ),
       'filter' => array(
       'id' => 'numeric',
    ),
  );

  $data['ek_address_book_contacts']['contact_name'] = array(
    'title' => t('contact name'),
    'help' => t('contact name'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['salutation'] = array(
    'title' => t('salutation'),
    'help' => t('contact greeting'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['title'] = array(
    'title' => t('title'),
    'help' => t('contact title'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['telephone'] = array(
    'title' => t('telephone'),
    'help' => t('contact telephone'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['mobilephone'] = array(
    'title' => t('mobilephone'),
    'help' => t('contact mobilephone'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['email'] = array(
    'title' => t('email'),
    'help' => t('contact email'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['card'] = array(
    'title' => t('name card image'),
    'help' => t('contact name card image fid.'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['department'] = array(
    'title' => t('department'),
    'help' => t('contact working department'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['link'] = array(
    'title' => t('link'),
    'help' => t('contact social media link'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );

  $data['ek_address_book_contacts']['comment'] = array(
    'title' => t('comment'),
    'help' => t('contact open comment.'),
    'field' => array(
      'id' => 'standard',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'string',
    ),
    'argument' => array(
      'id' => 'string',
    ),
  );
  
  $data['ek_address_book_contacts']['stamp'] = array(
    'title' => t('timestamp field'),
    'help' => t('timestamp field'),
    'field' => array(
      'id' => 'date',
    ),
    'sort' => array(
      'id' => 'date',
    ),
    'filter' => array(
      'id' => 'date',
    ),
  );

  return $data;
}



?>