<?php


/**
 * @file
 *  module ek_finance
 */

use Drupal\Core\Database\Database;
use Drupal\Component\Utility\Xss;
use Drupal\ek_finance\Journal;

/**
 * Implementation hook_ek_settings().
 * 
 */
function ek_finance_ek_settings($coids) {
    // we do not use param coids here as settings are global
    $settings = [];
    $query = Database::getConnection('external_db', 'external_db')
            ->select('ek_finance', 'f');
    $query->fields('f', ['id', 'settings']);
    $query->condition('id', '1');
    $data = $query->execute()->fetchObject();
    if ($data) {
        $settings = unserialize($data->settings);
    }

    $return = [];
    if (empty($settings)) {
        $_SESSION['install'] = 1;
        $link = \Drupal\Core\Url::fromRoute('ek_finance.admin.settings', [], [])->toString();
        $return['finance']['global'] = $link;
    }
    
    $co = [];
    foreach ($coids as $k => $id) {
        if($id > 0) {
            $fin = new \Drupal\ek_admin\CompanySettings($id);
            if(empty($fin->settings)) { 
                $link = \Drupal\Core\Url::fromRoute('ek_admin.company_settings.edit', ['id' => $id]);
                array_push($co, $link);
            }
        }
        if(!empty($co)) {
            $return['finance']['company'] = $co;
        }
        
    }
    
    if(!empty($return)) {
        return $return;
    }

    return new \Symfony\Component\HttpFoundation\Response('', 204);
}

/**
 * Implementation hook download.
 */
function ek_finance_file_download($uri) {

    if (strpos($uri, '/finance/')) {
        return array('Content-Type' => \Drupal::service('file.mime_type.guesser')->guessMimeType($uri));
    }
}

/**
 * Implementation hook ek_home.
 */
function ek_finance_ek_home() {
    $build = [];
    $build[] = [
        'name' => 'feature_1',
        'module' => 'Finance - Address book',
        'stamp' => 1587714990 ,
        'type' => "new",
        'content' => '<a href="/address_book">Bank details</a> can now be recorded in address book.',
        'footer' => 'April 2020',
    ];
    
    return $build;
}

/**
 * Implementation hook_theme().
 */
function ek_finance_theme() {
    return array(
        // for audits
        'ek_journal_audit' => [
            'template' => 'audit',
            'variables' => ['items' => []],
        ],
        'ek_finance_settings_form' => [
            'template' => 'ek_finance_settings',
            'variables' => ['items' => []],
        ],
        // for the dashboard
        'ek_finance_dashboard' => [
            'template' => 'ek_finance_dashboard',
            'variables' => ['items' => []],
        ],
        //expenses list
        'ek_finance_list_expenses' => [
            'template' => 'ek_finance_list_expenses',
            'variables' => ['items' => []],
        ],
        //monthly reoprt, budget
        'ek_finance_reporting' => [
            'template' => 'ek_finance_reporting',
            'variables' => ['items' => []],
        ],
        'ek_finance_reporting_compilation' => [
            'template' => 'ek_finance_reporting_compilation',
            'variables' => ['items' => []],
        ],
        'ek_finance_budgeting' => [
            'template' => 'ek_finance_budgeting',
            'variables' => ['items' => []],
        ],
        // for the journal items display
        'ek_finance_journal' => [
            'template' => 'ek_finance_journal',
            'variables' => ['items' => []],
        ],
        // for the journal items display by id
        'ek_finance_journal_by_id' => [
            'template' => 'ek_finance_journal_by_id',
            'variables' => ['items' => []],
        ],
        // for account history
        'ek_journal_history' => [
            'template' => 'ek_journal_history',
            'variables' => ['items' => []],
        ],
        // for the ledger items display
        'ek_finance_ledger' => [
            'template' => 'ek_finance_ledger',
            'variables' => ['items' => []],
        ],
        'ek_finance_sales_ledger' => [
            'template' => 'ek_finance_sales_ledger',
            'variables' => ['items' => []],
        ],
        // for the trial balalnce items display
        'ek_finance_trial' => [
            'template' => 'ek_finance_trial',
            'variables' => ['items' => []],
        ],
        // for the cash items display
        'ek_finance_cash' => [
            'template' => 'ek_finance_cash',
            'variables' => ['items' => []],
        ],
        // for the balance sheet
        'ek_balance_sheet' => [
            'template' => 'ek_balance_sheet',
            'variables' => ['items' => []],
        ],
        // for the memos transactions
        'ek_finance_memo_transactions' => [
            'template' => 'ek_finance_memo_transactions',
            'variables' => array('title' => NULL,
                'baseCurrency' => NULL,
                'form' => [],
                'companies' => [],
                'company_access' => [],
                'sum' => [],
                'due' => []),
        ],
        'ek_finance_memo_transactions_bycoid' => [
            'template' => 'ek_finance_memo_transactions_bycoid',
            'variables' => ['form' => [],
                'coid' => NULL,
                'baseCurrency' => NULL,
                'companies' => [],
                'transactions' => [],
                'sumCredit' => [],
                'sumDebit' => []
                ],
        ],
        // for the profit loss display
        'ek_profit_loss' => [
            'template' => 'ek_profit_loss',
            'variables' => ['items' => []],
        ],
        // for the tax report
        'ek_finance_tax' => [
            'template' => 'ek_finance_tax',
            'variables' => ['items' => []],
        ],
        // for cash flow statement
        'ek_finance_cashflow' => [
            'template' => 'ek_finance_cashflow',
            'variables' => ['items' => []],
        ],
        // for iframe display / pdf
        'iframe' => [
            'template' => 'iframe',
            'variables' => ['items' => []],
        ],
        // for AB items
        'ab_bank' => [
            'template' => 'ab_bank',
            'variables' => ['items' => []],
        ],
    );
}

/**
 * Return account history
 * @param
 * param = array()
 * id = a modal identifier
  aid = account id
 * coid = company id
 * from = from date
 * to = to date
 *
 */
function history($param) {

    $journal = new Journal();
    $history = $journal->history($param);
    return array(
        '#theme' => 'ek_journal_history',
        '#items' => unserialize($history),
        '#attached' => [
            'library' => ['ek_finance/ek_finance'],
        ],
    );
}

/**
 * Implementation hook_mail().
 */
function ek_finance_mail($key, &$message, $params) {

    $theme = theme_get_setting('logo');
    global $base_url;
    $params['options']['logo'] = $base_url . $theme['url'];
    $params['options']['site'] = \Drupal::config('system.site')->get('name');
    $params['options']['origin'] = \Drupal::currentUser()->getAccountName();
    $params['options']['stamp'] = date('F j, Y, g:i a');
    $site_mail = \Drupal::config('system.site')->get('mail');
    if (empty($site_mail)) {
        $site_mail = \Drupal::config('system.site')->get('mail_notification');
    }
    $message['headers']['Reply-To'] = $site_mail; 
    switch ($key) {
        case 'key_memo_note':
            $render = [
                '#markup' => $params['body'],
            ];
            $message['subject'] = $params['subject'];
            $message['body'][] = \Drupal::service('renderer')->render($render);
            $message['options'] = $params['options'];
            break;
    }
}

/**
 * Implements hook_form_alter().
 */
function ek_finance_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    if ($form_id == 'user_multiple_cancel_confirm') {

        $form['move_finance'] = [
            '#type' => 'textfield',
            '#title' => t('Move cash records'),
            '#autocomplete_route_name' => 'ek_admin.user_autocomplete',
            '#description' => t('Select to whom to transfer cash records'),
        ];
        $form['#validate'][] = 'ek_finance_form_user_delete_validate';
        $form['#submit'][] = 'ek_finance_form_user_delete_submit';

        return $form;
    }
}

/**
 * Implements hook_form_validate().
 */
function ek_finance_form_user_delete_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {

    if ($form['#form_id'] == 'user_multiple_cancel_confirm') {
        if ($form_state->getValue('move_finance') <> '') {
            $query = Database::getConnection()->select('users_field_data', 'u');
            $query->fields('u', ['uid']);
            $query->condition('name', $form_state->getValue('move_finance'));
            $data = $query->execute()->fetchField();

            if ($data) {
                $form_state->setValue('move_finance', $data);
            } else {
                $form_state->setErrorByName('move_finance', t('Unknown user to move documents'));
            }
        }

        return $form;
    }
}

/**
 * Implements hook_form_submit().
 */
function ek_finance_form_user_delete_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {

    if ($form['#form_id'] == 'user_multiple_cancel_confirm') {
        if ($form_state->getValue('move_finance')) {
            foreach ($form_state->getValue('accounts') as $key => $id) {

                $query = Database::getConnection('external_db', 'external_db')
                        ->select('ek_cash', 'c');
                $query->fields('c', ['id', 'comment']);
                $query->condition('uid', $id);
                $c = $query->execute();
                while ($list = $c->fetchObject()) {
                    $comment = "(" . t('Moved from user @u', ['@u' => $id]) . ") " . $list->comment;
                    $query = Database::getConnection('external_db', 'external_db')
                                    ->update('ek_cash')
                                    ->fields(['uid' => $form_state->getValue('move_finance'), 'comment' => $comment])
                                    ->condition('id', $list->id)->execute();
                }

                $query = Database::getConnection('external_db', 'external_db')
                        ->select('ek_expenses', 'e');
                $query->fields('e', ['id', 'comment']);
                $query->condition('employee', $id);
                $e = $query->execute();
                while ($list = $e->fetchObject()) {
                    $comment = "(" . t('Moved from user @u', ['@u' => $id]) . ") " . $list->comment;
                    $query = Database::getConnection('external_db', 'external_db')
                                    ->update('ek_expenses')
                                    ->fields(['employee' => $form_state->getValue('move_finance'), 'comment' => $comment])
                                    ->condition('id', $list->id)->execute();
                }
            }
        }
        \Drupal::messenger()->addStatus(t('Cash records moved to user @u', ['@u' => $form_state->getValue('move_finance')]));
        return $form;
    }
}

/**
 * Implements hook_form_ID_alter().
 * add bank details info
 */
function ek_finance_form_ek_edit_address_book_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    
    $form['bank'] = array(
        '#type' => 'details',
        '#title' => t('Bank information'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );
    
    $query = Database::getConnection('external_db', 'external_db')
                ->select('ek_address_book_bank', 'b');
    $query->fields('b');
    $query->condition('abid', $form['for_id']['#value']);
    $banks = $query->execute();
    $i = 0;
    $currencies = ['0' => t('Any')];
    $currencies += \Drupal\ek_finance\CurrencyData::listcurrency();
                
    while ($bank = $banks->fetchObject()) {
        $i++;
        $form['bank']['edit' . $i] = [
            '#title' => t('Edit') . " : " . $bank->name,
            '#type' => 'details',
            '#collapsed' => true,
        ];
        
        $form['bank']['edit' . $i]["bid-" . $i] = [
            '#type' => 'hidden',
            '#value' => $bank->id,
        ];
        
        $form['bank']['edit' . $i]["currency" . $i] = [
            '#type' => 'select',
            '#size' => 1,
            '#options' => $currencies,
            '#description' => t('currency'),
            '#default_value' => $bank->currency,
        ];
        
        
        $form['bank']['edit' . $i]["bname" . $i] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#default_value' => $bank->name,
            '#attributes' => array('placeholder' => t('bank name')),
        ];
        
        $form['bank']['edit' . $i]["beneficiary" . $i] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#default_value' => $bank->beneficiary,
            '#attributes' => array('placeholder' => t('beneficiary')),
        ];

        $form['bank']['edit' . $i]["baddress1" . $i] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#default_value' => $bank->address1,
            '#attributes' => array('placeholder' => t('address line 1')),
        ];

        $form['bank']['edit' . $i]["baddress2" . $i] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#default_value' => $bank->address2,
            '#attributes' => array('placeholder' => t('address line 2')),
        ];

        $form['bank']['edit' . $i]["bpostcode" . $i] = [
            '#type' => 'textfield',
            '#size' => 10,
            '#maxlength' => 30,
            '#default_value' => $bank->postcode,
            '#attributes' => array('placeholder' => t('postcode')),
        ];
       
        $form['bank']['edit' . $i]['bank_country' . $i] = $form['country'];
        $form['bank']['edit' . $i]['bank_country' . $i]['#default_value'] = $bank->country;

        $form['bank']['edit' . $i]['account' . $i] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#default_value' => $bank->account,
            '#maxlength' => 40,
            '#attributes' => array('placeholder' => t('account')),
        ];

        $form['bank']['edit' . $i]['bank_code' . $i] = [
            '#type' => 'textfield',
            '#size' => 25,
            '#maxlength' => 25,
            '#default_value' => $bank->bank_code,
            '#attributes' => array('placeholder' => t('bank code')),
        ];

        $form['bank']['edit' . $i]['swift' . $i] = [
            '#type' => 'textfield',
            '#size' => 25,
            '#maxlength' => 25,
            '#default_value' => $bank->swift,
            '#attributes' => array('placeholder' => t('swift code')),
        ];

    }
    
    $form['count'] = [
            '#type' => 'hidden',
            '#value' => $i,
    ];
     
    //if ($form['for_id']) {
        $form['bank']['new'] = [
            '#title' => t('Add new'),
            '#type' => 'details',
            '#open' => true,
        ];
        
        $form['bank']['new']["bname"] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 250,
            '#description' => '',
            '#attributes' => array('placeholder' => t('bank name')),
        ];
        
        $form['bank']['new']["beneficiary"] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 250,
            '#description' => '',
            '#attributes' => array('placeholder' => t('beneficiary name')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];

        $form['bank']['new']["currency"] = [
            '#type' => 'select',
            '#size' => 1,
            '#options' => $currencies,
            '#description' => t('currency'),
            '#default_value' => 0,
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];
        $form['bank']['new']["baddress1"] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#description' => '',
            '#attributes' => array('placeholder' => t('address line 1')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];

        $form['bank']['new']["baddress2"] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 255,
            '#description' => '',
            '#attributes' => array('placeholder' => t('address line 2')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];

        $form['bank']['new']["bpostcode"] = [
            '#type' => 'textfield',
            '#size' => 10,
            '#maxlength' => 30,
            '#description' => '',
            '#attributes' => array('placeholder' => t('postcode')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];
       
        $form['bank']['new']['bank_country'] = $form['country'];
        $form['bank']['new']['bank_country']['#required'] = false;
        $form['bank']['new']['bank_country']['#states'] = [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ];

        $form['bank']['new']['account'] = [
            '#type' => 'textfield',
            '#size' => 40,
            '#maxlength' => 40,
            '#attributes' => array('placeholder' => t('account')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];

        $form['bank']['new']['bank_code'] = [
            '#type' => 'textfield',
            '#size' => 25,
            '#maxlength' => 25,
            '#attributes' => array('placeholder' => t('bank code')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];

        $form['bank']['new']['swift'] = [
            '#type' => 'textfield',
            '#size' => 25,
            '#maxlength' => 20,
            '#attributes' => array('placeholder' => t('swift code')),
            '#states' => [
                'invisible' => [
                    "input[name='bname']" => ['value' => ''],
                ],
            ],
        ];
    //}
    /*
    $form['tax'] = array(
        '#type' => 'details',
        '#title' => t('Tax information'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );
    if (!$form['for_id']) {
        $form['tax']['tax_code'] = array(
            '#type' => 'textfield',
            '#size' => 25,
            '#maxlength' => 20,
            '#attributes' => array('placeholder' => t('tax code')),
        );
    }*/
    
    $form['#validate'][] = 'ek_finance_ab_bank_validate';
    $form['#submit'][] = 'ek_fiance_ab_bank_submit';
    return $form;
}

/**
 * Implements hook_form_validate().
 */
function ek_finance_ab_bank_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
    
}
/**
 * Implements hook_form_submit().
 */
function ek_fiance_ab_bank_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
    
    
    if($form_state->getValue('count') > 0) {
        for($i = 1; $i <= $form_state->getValue('count'); $i++) {
            $fields = array(
                    'name' => Xss::filter($form_state->getValue('bname' . $i)),
                    'beneficiary' => Xss::filter($form_state->getValue('beneficiary' . $i)),
                    'address1' => Xss::filter($form_state->getValue('baddress1' . $i)),
                    'address2' => Xss::filter($form_state->getValue('baddress2' . $i)),
                    'postcode' => Xss::filter($form_state->getValue('bpostcode' . $i)),
                    'country' => $form_state->getValue('bank_country' . $i),
                    'account' => Xss::filter($form_state->getValue('account' . $i)),
                    'bank_code' => Xss::filter($form_state->getValue('bank_code' . $i)),
                    'swift' => Xss::filter($form_state->getValue('swift' . $i)),
                    'currency' => $form_state->getValue('currency' . $i),
                    'abid' => $form_state->getValue('for_id'),
                    
            );
            
            $query = Database::getConnection('external_db', 'external_db')
                ->update('ek_address_book_bank')
                ->fields($fields)
                ->condition('id', $form_state->getValue('bid-' . $i));
            $query->execute();
        
        }
    }
    
    
    if($form_state->getValue('bname') != NULL) {
        if($form_state->getValue('for_id') == '') {
            //retrieve the last id record
             $query = Database::getConnection('external_db', 'external_db')
                ->select('ek_address_book', 'a');
             $query->fields('a',['id']);
             $query->range(0,1);
             $query->orderBy('id', 'DESC');
             $id = $query->execute()->fetchField();
        } else {
            $id = $form_state->getValue('for_id');
        }
        $fields = array(
                    'name' => Xss::filter($form_state->getValue('bname')),
                    'beneficiary' => Xss::filter($form_state->getValue('beneficiary')),
                    'address1' => Xss::filter($form_state->getValue('baddress1')),
                    'address2' => Xss::filter($form_state->getValue('baddress2')),
                    'postcode' => Xss::filter($form_state->getValue('bpostcode')),
                    'country' => $form_state->getValue('bank_country'),
                    'account' => Xss::filter($form_state->getValue('account')),
                    'bank_code' => Xss::filter($form_state->getValue('bank_code')),
                    'swift' => Xss::filter($form_state->getValue('swift')),
                    'abid' => $id,
                    'currency' => $form_state->getValue('currency'),
        );
        $query = Database::getConnection('external_db', 'external_db')
                ->insert('ek_address_book_bank')
                ->fields($fields);
        $query->execute();
        
    }
    
    \Drupal\Core\Cache\Cache::invalidateTags(['ab_bank_' . $form_state->getValue('for_id')]);
}
