<?php

use Drupal\Core\Database\Database;

/**
 * Implementation hook_ek_settings().
 * 
 */
function ek_logistics_ek_settings($coids) {

    $flag = 0;

    foreach ($coids as $key => $id) {
        if ($id > 0) {
            $settings = [];
            $query = Database::getConnection('external_db', 'external_db')
                    ->select('ek_logi_settings', 'l');
            $query->fields('l', ['coid', 'settings']);
            $query->condition('coid', $id);
            $data = $query->execute()->fetchObject();
            if ($data) {
                $settings = unserialize($data->settings);
            }
            if (empty($settings)) {
                $link = \Drupal\Core\Url::fromRoute('ek_logistics_settings', array(), array())->toString();
                $_SESSION['install'] = 1;
                $flag = 1;
            }
        }
    }

    if ($flag == 1) {
        return ['logistics' => $link];
    } else {
        return new \Symfony\Component\HttpFoundation\Response('', 204);
    }
}


/**
 * Implementation hook_theme().
 */
function ek_logistics_theme() {
    return [
        'ek_logistics_dashboard' => [
            'template' => 'ek_logistics_dashboard',
            'variables' => ['items' => []],
        ],
        'iframe' => [
            'template' => 'iframe',
            'variables' => ['items' => []],
        ],
        'default_logi_delivery' => [
            'template' => 'default_logi_delivery',
            'variables' => ['content' => []],
        ],
        'default_logi_receiving' => [
            'template' => 'default_logi_receiving',
            'variables' => ['content' => []],
        ],
        'default_logi_returning' => [
            'template' => 'default_logi_returning',
            'variables' => ['content' => []],
        ],

    ];
}

/*
 * Adjust stock quantity
 * @param Char $itemcode
 * @param double $value
 * @param action -/+
 */

function ek_logistics_stock_adjust($itemcode, $value, $action) {

    if ($action == '-') {
        $query = 'UPDATE {ek_item_packing} SET units = units - :u WHERE itemcode = :i';
    }

    if ($action == '+') {
        $query = 'UPDATE {ek_item_packing} SET units = units - :u WHERE itemcode = :i';
    }

    $a = array(':u' => $value, ':i' => $itemcode);
    $data = Database::getConnection('external_db', 'external_db')
            ->query($query, $a);

    if ($data) {
        return TRUE;
    }
}
