<?php

    ///////////////////////////////////////////////////
    //                  COPYRIGHT                    //
    //                                               //
    // DEVELOPPED BY ARREA LTD                       //
    // all rights reserved                           //
    // Please read and agree with software           //
    // application license                           //
    ///////////////////////////////////////////////////

/**
 * @file
 *  module . ek_assets
 */


/**
 * Implementation hook_theme().
 */
function ek_assets_theme() {
  return array(
    'ek_assets_list' => array
    (
      'template' => 'ek_assets_list',
      'variables' => array('items' => array()),
    ),
    'ek_assets_card' => array
    (
      'template' => 'ek_assets_card',
      'variables' => array('items' => array()),
    ),
    // for the dashboard
    'ek_assets_dashboard' => array
    (
      'template' => 'ek_assets_dashboard',
      'variables' => array('items' => array()),
    ), 
  );
}

/**
 * Implementation hook download.
 */
function ek_assets_file_download($uri) {

    if (strpos($uri,'/assets/')) {
        return array('Content-Type' => \Drupal::service('file.mime_type.guesser')->guess($uri));
    }
}


