<?php


/**
 * @file
 *  module .
 */

/**
 * Implements hook_file_download().
 *
 * edit the file_download function in order to control access of items images
*/
function ek_products_file_download($uri) {
    if( strpos($uri , 'products/images' )  ) { 
        $guesser = \Drupal::service('file.mime_type.guesser');
        $mime = $guesser->guessMimeType($uri);
        return array('Content-Type' => $mime); 
    }
}

/**
 * Implementation hook_theme().
 */
function ek_products_theme() {
  return array(

    // for the lookup item form
    'ek_products_search_form' => array
    (
      'template' => 'ek_products_search_form',
      'variables' => array('items' => array()),
    ), 
    
    // for the item display
    'ek_products_card' => array
    (
      'template' => 'ek_products_card',
      'variables' => array('items' => array()),
    ),   

    // for the item form edit
    'ek_products_form' => array
    (
      'template' => 'ek_products_form',
      'variables' => array('items' => array(), 'fields' => array()),
    ), 
        
  );     
}

/**
 * Preprocess variables for items.
 *
 * @param array $variables
 *  An associative array containing:
 *  - items: 
 */
 
function template_preprocess_ek_products_search_form(&$variables) {


}

function template_preprocess_ek_products_card(&$variables) {                                 

  
}

/**
 * Preprocess variables for  views.
 *
 * @param array $variables
 *  An associative array containing:
 *  - items: 
 */


function template_preprocess_ek_products_form(&$variables) {

//$variables['search_link'] = l(t('New seach'), 'item_search');


}
